PACKAGE_NAME="linuwu-sense"
PACKAGE_VERSION="25.701"
MAKE[0]="make -C $kernel_source_dir M=$dkms_tree/$module/$module_version/build modules"
BUILT_MODULE_NAME[0]="linuwu_sense"
BUILT_MODULE_LOCATION[0]="src/"
DEST_MODULE_LOCATION[0]="/kernel/drivers/platform/x86"
AUTOINSTALL="yes"
BUILD_EXCLUSIVE_KERNEL_MIN=6.16
